package ui

import "github.com/charmbracelet/bubbles/key"

// GlobalKeys are recognized everywhere except inside a focused text input.
type GlobalKeys struct {
	Up       key.Binding
	Down     key.Binding
	Top      key.Binding
	Bottom   key.Binding
	Tab      key.Binding
	ShiftTab key.Binding
	HalfDown key.Binding
	HalfUp   key.Binding
	Escape   key.Binding
	Leader   key.Binding
	Enter    key.Binding
	Filter   key.Binding
}

// Keys is the single source of truth for gl-pipe's key bindings. The README
// keyboard table is generated by hand from this file — when a binding
// changes here, update README.md's table to match.
var Keys = GlobalKeys{
	Up:       key.NewBinding(key.WithKeys("k", "up"), key.WithHelp("k/↑", "up")),
	Down:     key.NewBinding(key.WithKeys("j", "down"), key.WithHelp("j/↓", "down")),
	Top:      key.NewBinding(key.WithKeys("g"), key.WithHelp("g", "top")),
	Bottom:   key.NewBinding(key.WithKeys("G"), key.WithHelp("G", "bottom")),
	Tab:      key.NewBinding(key.WithKeys("tab"), key.WithHelp("tab", "next pane")),
	ShiftTab: key.NewBinding(key.WithKeys("shift+tab"), key.WithHelp("shift+tab", "prev pane")),
	HalfDown: key.NewBinding(key.WithKeys("ctrl+d"), key.WithHelp("ctrl+d", "half-page down")),
	HalfUp:   key.NewBinding(key.WithKeys("ctrl+u"), key.WithHelp("ctrl+u", "half-page up")),
	Escape:   key.NewBinding(key.WithKeys("esc"), key.WithHelp("esc", "dismiss/back")),
	Leader:   key.NewBinding(key.WithKeys(" "), key.WithHelp("space", "leader menu")),
	Enter:    key.NewBinding(key.WithKeys("enter"), key.WithHelp("enter", "select")),
	Filter:   key.NewBinding(key.WithKeys("/"), key.WithHelp("/", "filter/search")),
}

// LeaderAction is one mnemonic entry in the <Space> leader menu.
type LeaderAction struct {
	Key   string
	Label string
}

// LeaderActions is the full leader menu, in display order.
var LeaderActions = []LeaderAction{
	{Key: "p", Label: "trigger pipeline"},
	{Key: "f", Label: "blob search filter"},
	{Key: "b", Label: "search pipelines by ref"},
	{Key: "v", Label: "variable preset"},
	{Key: "g", Label: "discover groups"},
	{Key: "s", Label: "settings / instances"},
	{Key: "o", Label: "open in browser"},
	{Key: "r", Label: "force refresh"},
	{Key: "q", Label: "quit"},
}

// Explorer-specific keys.
var (
	KeyToggleSelect   = key.NewBinding(key.WithKeys("x"), key.WithHelp("x", "toggle select"))
	KeyLockLatestTag  = key.NewBinding(key.WithKeys("T"), key.WithHelp("T", "lock latest semver tag"))
	KeyOpenBrowserAlt = key.NewBinding(key.WithKeys("g", "x"), key.WithHelp("gx", "open in browser"))
)

// Pipeline/job matrix keys.
var (
	KeyBulkRetry  = key.NewBinding(key.WithKeys("R"), key.WithHelp("R", "bulk retry"))
	KeyBulkCancel = key.NewBinding(key.WithKeys("K"), key.WithHelp("K", "bulk cancel"))
)

// Log viewer keys.
var (
	KeyJumpToError = key.NewBinding(key.WithKeys("E"), key.WithHelp("E", "jump to first error"))
)

// Variable table editing keys.
var (
	KeyAddVar          = key.NewBinding(key.WithKeys("a"), key.WithHelp("a", "add variable"))
	KeyDeleteVar       = key.NewBinding(key.WithKeys("d"), key.WithHelp("d", "delete variable"))
	KeyToggleVarType   = key.NewBinding(key.WithKeys("t"), key.WithHelp("t", "toggle env/file"))
	KeyToggleMasked    = key.NewBinding(key.WithKeys("m"), key.WithHelp("m", "toggle masked"))
	KeyToggleProtected = key.NewBinding(key.WithKeys("p"), key.WithHelp("p", "toggle protected"))
)
